import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Syncopate } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const syncopate = Syncopate({ 
  weight: ["400", "700"], 
  subsets: ["latin"],
  variable: "--font-syncopate" 
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${syncopate.variable} font-sans bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}
